"""Closed parser formats and stable error identifiers."""

from __future__ import annotations

from enum import StrEnum


class ParserFormat(StrEnum):
    """Formats admitted by the frozen C1 router."""

    TXT = "txt"
    MARKDOWN = "markdown"
    HTML = "html"
    DOCX = "docx"
    PPTX = "pptx"
    XLSX = "xlsx"
    CSV = "csv"
    PDF = "pdf"
    SYNTHETIC_MINERU_ARTIFACT = "synthetic_mineru_artifact"


class StableErrorCode(StrEnum):
    """The complete parser-stable-error.v1 code set."""

    FORMAT_MISMATCH = "FORMAT_MISMATCH"
    FORMAT_AMBIGUOUS = "FORMAT_AMBIGUOUS"
    FORMAT_UNSUPPORTED = "FORMAT_UNSUPPORTED"
    INPUT_INVALID = "INPUT_INVALID"
    INPUT_TOO_LARGE = "INPUT_TOO_LARGE"
    PAGE_LIMIT_EXCEEDED = "PAGE_LIMIT_EXCEEDED"
    ARCHIVE_LIMIT_EXCEEDED = "ARCHIVE_LIMIT_EXCEEDED"
    ENCODING_AMBIGUOUS = "ENCODING_AMBIGUOUS"
    ACTIVE_CONTENT_UNSUPPORTED = "ACTIVE_CONTENT_UNSUPPORTED"
    PDF_ENCRYPTED_UNSUPPORTED = "PDF_ENCRYPTED_UNSUPPORTED"
    MINERU_REQUIRED = "MINERU_REQUIRED"
    PROTOCOL_INVALID = "PROTOCOL_INVALID"
    RESULT_TOO_LARGE = "RESULT_TOO_LARGE"
    PARSER_BUSY = "PARSER_BUSY"
    PARSER_CANCELLED = "PARSER_CANCELLED"
    PARSER_TIMEOUT = "PARSER_TIMEOUT"
    PARSER_MEMORY_LIMIT = "PARSER_MEMORY_LIMIT"
    PARSER_SANDBOX_UNAVAILABLE = "PARSER_SANDBOX_UNAVAILABLE"
    PARSER_SCHEMA_MISMATCH = "PARSER_SCHEMA_MISMATCH"
    PARSER_NONDETERMINISTIC = "PARSER_NONDETERMINISTIC"
    QUALITY_LOCATOR_FAILED = "QUALITY_LOCATOR_FAILED"
    QUALITY_CHUNK_BOUNDARY_FAILED = "QUALITY_CHUNK_BOUNDARY_FAILED"


CONTROLLER_ONLY_ERRORS = frozenset(
    {
        StableErrorCode.PARSER_CANCELLED,
        StableErrorCode.PARSER_SANDBOX_UNAVAILABLE,
    }
)
WIRE_FAILURE_ERRORS = (
    frozenset(StableErrorCode)
    - CONTROLLER_ONLY_ERRORS
    - {
        StableErrorCode.MINERU_REQUIRED,
    }
)
