package agentrunner

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"time"
)

// NewRequest constructs one strict outbound Runner RPC envelope with fresh
// cryptographic replay identifiers. Callers cannot provide or reuse a nonce.
func NewRequest(method string, body any, now time.Time) (Request, error) {
	if now.IsZero() {
		return Request{}, ErrInvalidInput
	}
	requestBytes := make([]byte, 16)
	nonceBytes := make([]byte, 32)
	if _, err := rand.Read(requestBytes); err != nil {
		return Request{}, ErrRuntimeUnavailable
	}
	if _, err := rand.Read(nonceBytes); err != nil {
		return Request{}, ErrRuntimeUnavailable
	}
	envelope, err := json.Marshal(struct {
		SchemaVersion string    `json:"schemaVersion"`
		Method        string    `json:"method"`
		RequestID     string    `json:"requestId"`
		SentAt        time.Time `json:"sentAt"`
		Nonce         string    `json:"nonce"`
		Body          any       `json:"body"`
	}{
		SchemaVersion: ProtocolVersion,
		Method:        method,
		RequestID:     "rpc_" + hex.EncodeToString(requestBytes),
		SentAt:        now.UTC(),
		Nonce:         base64.RawURLEncoding.EncodeToString(nonceBytes),
		Body:          body,
	})
	if err != nil {
		return Request{}, ErrInvalidInput
	}
	return DecodeRequest(envelope, now.UTC(), time.Second)
}

// BindAuthority attaches a signed authority ticket without changing the
// replay identifiers generated by NewRequest. PostgreSQL authority issuance
// and the bytes sent to the Runner therefore describe one exact request.
func BindAuthority(request Request, ticket AuthorityTicket) (Request, error) {
	if len(request.Canonical) == 0 || validateAuthorityClaims(ticket.AuthorityClaims) != nil ||
		ticket.Method != request.Method || ticket.RequestID != request.RequestID || ticket.Nonce != request.Nonce {
		return Request{}, ErrInvalidInput
	}
	var body any
	switch request.Method {
	case MethodLaunch:
		if request.Launch == nil {
			return Request{}, ErrInvalidInput
		}
		value := *request.Launch
		value.Authority = ticket
		body = value
	case MethodHeartbeat:
		if request.Heartbeat == nil {
			return Request{}, ErrInvalidInput
		}
		value := *request.Heartbeat
		value.Authority = ticket
		body = value
	case MethodCancel:
		if request.Cancel == nil {
			return Request{}, ErrInvalidInput
		}
		value := *request.Cancel
		value.Authority = ticket
		body = value
	case MethodPrepare:
		if request.Prepare == nil {
			return Request{}, ErrInvalidInput
		}
		value := *request.Prepare
		value.Authority = ticket
		body = value
	case MethodCommit:
		if request.Commit == nil {
			return Request{}, ErrInvalidInput
		}
		value := *request.Commit
		value.Authority = ticket
		body = value
	default:
		return Request{}, ErrInvalidInput
	}
	if ticket.RequestFingerprint != AuthorityRequestFingerprint(request.Method, body) {
		return Request{}, ErrInvalidInput
	}
	envelope, err := json.Marshal(struct {
		SchemaVersion string    `json:"schemaVersion"`
		Method        string    `json:"method"`
		RequestID     string    `json:"requestId"`
		SentAt        time.Time `json:"sentAt"`
		Nonce         string    `json:"nonce"`
		Body          any       `json:"body"`
	}{request.SchemaVersion, request.Method, request.RequestID, request.SentAt, request.Nonce, body})
	if err != nil {
		return Request{}, ErrInvalidInput
	}
	return DecodeRequest(envelope, request.SentAt, time.Second)
}
