-- Initial Postgres persistence skeleton for mm-chat.
-- All UUID primary keys are generated by the Go application. This migration
-- intentionally avoids extension dependencies, database-side UUID generation,
-- and enum types.

CREATE TABLE users (
  id UUID PRIMARY KEY,
  email TEXT UNIQUE,
  display_name TEXT NOT NULL DEFAULT '',
  avatar_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT users_email_not_blank CHECK (email IS NULL OR length(trim(email)) > 0),
  CONSTRAINT users_timestamps_order CHECK (updated_at >= created_at),
  CONSTRAINT users_deleted_after_created CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

CREATE TABLE sessions (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  user_agent TEXT,
  ip_address INET,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT sessions_token_hash_not_blank CHECK (length(trim(token_hash)) > 0),
  CONSTRAINT sessions_expires_after_created CHECK (expires_at > created_at),
  CONSTRAINT sessions_revoked_after_created CHECK (revoked_at IS NULL OR revoked_at >= created_at),
  CONSTRAINT sessions_timestamps_order CHECK (updated_at >= created_at)
);

CREATE TABLE conversations (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  model_provider TEXT,
  model_id TEXT,
  system_prompt TEXT,
  idempotency_key TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT conversations_status_check CHECK (status IN ('active', 'archived', 'deleted')),
  CONSTRAINT conversations_idempotency_key_not_blank CHECK (idempotency_key IS NULL OR length(trim(idempotency_key)) > 0),
  CONSTRAINT conversations_metadata_object CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT conversations_timestamps_order CHECK (updated_at >= created_at),
  CONSTRAINT conversations_deleted_after_created CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

CREATE TABLE provider_configs (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider_id TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  encrypted_secret_ref TEXT,
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT provider_configs_provider_id_not_blank CHECK (length(trim(provider_id)) > 0),
  CONSTRAINT provider_configs_secret_ref_not_blank CHECK (encrypted_secret_ref IS NULL OR length(trim(encrypted_secret_ref)) > 0),
  CONSTRAINT provider_configs_config_object CHECK (jsonb_typeof(config) = 'object'),
  CONSTRAINT provider_configs_timestamps_order CHECK (updated_at >= created_at),
  CONSTRAINT provider_configs_deleted_after_created CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

CREATE TABLE files (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  original_filename TEXT NOT NULL,
  mime_type TEXT NOT NULL DEFAULT 'application/octet-stream',
  byte_size BIGINT NOT NULL,
  sha256 TEXT NOT NULL,
  storage_backend TEXT NOT NULL DEFAULT 'minio',
  object_key TEXT NOT NULL,
  upload_status TEXT NOT NULL DEFAULT 'available',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT files_original_filename_not_blank CHECK (length(trim(original_filename)) > 0),
  CONSTRAINT files_mime_type_not_blank CHECK (length(trim(mime_type)) > 0),
  CONSTRAINT files_byte_size_non_negative CHECK (byte_size >= 0),
  CONSTRAINT files_sha256_hex_check CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT files_storage_backend_check CHECK (storage_backend IN ('local', 'minio', 's3')),
  CONSTRAINT files_object_key_not_blank CHECK (length(trim(object_key)) > 0),
  CONSTRAINT files_object_key_not_absolute CHECK (object_key !~ '^/'),
  CONSTRAINT files_object_key_unique UNIQUE (object_key),
  CONSTRAINT files_upload_status_check CHECK (upload_status IN ('pending', 'available', 'failed', 'deleted')),
  CONSTRAINT files_metadata_object CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT files_timestamps_order CHECK (updated_at >= created_at),
  CONSTRAINT files_deleted_after_created CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

CREATE TABLE messages (
  id UUID PRIMARY KEY,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  parent_message_id UUID REFERENCES messages(id) ON DELETE SET NULL,
  sequence_no INTEGER NOT NULL,
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'completed',
  content TEXT NOT NULL DEFAULT '',
  model_provider TEXT,
  model_id TEXT,
  provider_message_id TEXT,
  idempotency_key TEXT,
  output_blocks JSONB NOT NULL DEFAULT '[]'::jsonb,
  error_code TEXT,
  error_message TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT messages_sequence_non_negative CHECK (sequence_no >= 0),
  CONSTRAINT messages_conversation_sequence_unique UNIQUE (conversation_id, sequence_no),
  CONSTRAINT messages_role_check CHECK (role IN ('system', 'user', 'assistant', 'tool')),
  CONSTRAINT messages_status_check CHECK (status IN ('pending', 'streaming', 'completed', 'failed', 'cancelled')),
  CONSTRAINT messages_idempotency_key_not_blank CHECK (idempotency_key IS NULL OR length(trim(idempotency_key)) > 0),
  CONSTRAINT messages_output_blocks_array CHECK (jsonb_typeof(output_blocks) = 'array'),
  CONSTRAINT messages_metadata_object CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT messages_timestamps_order CHECK (updated_at >= created_at),
  CONSTRAINT messages_completed_after_created CHECK (completed_at IS NULL OR completed_at >= created_at),
  CONSTRAINT messages_deleted_after_created CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

CREATE TABLE message_attachments (
  id UUID PRIMARY KEY,
  message_id UUID NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  file_id UUID NOT NULL REFERENCES files(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  display_order INTEGER NOT NULL DEFAULT 0,
  purpose TEXT NOT NULL DEFAULT 'input',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT message_attachments_message_file_unique UNIQUE (message_id, file_id),
  CONSTRAINT message_attachments_display_order_non_negative CHECK (display_order >= 0),
  CONSTRAINT message_attachments_purpose_check CHECK (purpose IN ('input', 'output', 'image', 'knowledge_source')),
  CONSTRAINT message_attachments_timestamps_order CHECK (updated_at >= created_at)
);

CREATE TABLE audit_logs (
  id UUID PRIMARY KEY,
  actor_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  session_id UUID REFERENCES sessions(id) ON DELETE SET NULL,
  conversation_id UUID REFERENCES conversations(id) ON DELETE SET NULL,
  message_id UUID REFERENCES messages(id) ON DELETE SET NULL,
  file_id UUID REFERENCES files(id) ON DELETE SET NULL,
  actor_type TEXT NOT NULL DEFAULT 'user',
  action TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id UUID,
  request_id TEXT,
  outcome TEXT NOT NULL DEFAULT 'success',
  ip_address INET,
  user_agent TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_actor_type_check CHECK (actor_type IN ('anonymous', 'user', 'admin', 'system', 'service')),
  CONSTRAINT audit_logs_action_not_blank CHECK (length(trim(action)) > 0),
  CONSTRAINT audit_logs_resource_type_not_blank CHECK (length(trim(resource_type)) > 0),
  CONSTRAINT audit_logs_outcome_check CHECK (outcome IN ('success', 'denied', 'failed', 'cancelled')),
  CONSTRAINT audit_logs_metadata_object CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT audit_logs_timestamps_order CHECK (updated_at >= created_at)
);

CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX idx_sessions_active_user ON sessions(user_id, expires_at) WHERE revoked_at IS NULL;

CREATE INDEX idx_conversations_user_updated ON conversations(user_id, updated_at DESC);
CREATE INDEX idx_conversations_user_active ON conversations(user_id, updated_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_conversations_status ON conversations(status);
CREATE UNIQUE INDEX idx_conversations_user_idempotency ON conversations(user_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE INDEX idx_provider_configs_user_provider ON provider_configs(user_id, provider_id);
CREATE INDEX idx_provider_configs_user_active ON provider_configs(user_id, provider_id) WHERE deleted_at IS NULL;

CREATE INDEX idx_files_user_created ON files(user_id, created_at DESC);
CREATE INDEX idx_files_sha256 ON files(sha256);
CREATE INDEX idx_files_upload_status ON files(upload_status);
CREATE INDEX idx_files_user_active ON files(user_id, created_at DESC) WHERE deleted_at IS NULL;

CREATE INDEX idx_messages_conversation_created ON messages(conversation_id, created_at);
CREATE INDEX idx_messages_conversation_role ON messages(conversation_id, role);
CREATE INDEX idx_messages_status ON messages(status);
CREATE INDEX idx_messages_user_id ON messages(user_id);
CREATE INDEX idx_messages_parent_message_id ON messages(parent_message_id);
CREATE UNIQUE INDEX idx_messages_conversation_idempotency ON messages(conversation_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE INDEX idx_message_attachments_file_id ON message_attachments(file_id);
CREATE INDEX idx_message_attachments_user_id ON message_attachments(user_id);

CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX idx_audit_logs_actor_created ON audit_logs(actor_user_id, created_at DESC);
CREATE INDEX idx_audit_logs_session_created ON audit_logs(session_id, created_at DESC);
CREATE INDEX idx_audit_logs_resource ON audit_logs(resource_type, resource_id, created_at DESC);
CREATE INDEX idx_audit_logs_outcome_created ON audit_logs(outcome, created_at DESC);
CREATE INDEX idx_audit_logs_request_id ON audit_logs(request_id) WHERE request_id IS NOT NULL;
