-- Phase 15.1A identity, team, knowledge ACL, governance, consent, and outbox
-- schema foundation. UUID values are generated by the Go application.

ALTER TABLE users
  ADD COLUMN account_status TEXT NOT NULL DEFAULT 'active';

ALTER TABLE users
  ADD CONSTRAINT users_account_status_check
  CHECK (account_status IN ('active', 'disabled'));

CREATE UNIQUE INDEX idx_users_email_case_insensitive
  ON users(lower(email))
  WHERE email IS NOT NULL;

CREATE TABLE user_credentials (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  password_hash TEXT NOT NULL,
  credential_revision BIGINT NOT NULL DEFAULT 1,
  email_verified_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_credentials_password_hash_argon2id_check
    CHECK (password_hash ~ '^\$argon2id\$' AND password_hash = trim(password_hash)),
  CONSTRAINT user_credentials_revision_positive
    CHECK (credential_revision >= 1),
  CONSTRAINT user_credentials_timestamps_order
    CHECK (updated_at >= created_at)
);

CREATE TABLE credential_recovery_tokens (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'active',
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT credential_recovery_tokens_hash_check
    CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT credential_recovery_tokens_status_check
    CHECK (status IN ('active', 'used', 'revoked')),
  CONSTRAINT credential_recovery_tokens_status_timestamps_check CHECK (
    (status = 'active' AND used_at IS NULL AND revoked_at IS NULL)
    OR (status = 'used' AND used_at IS NOT NULL AND revoked_at IS NULL)
    OR (status = 'revoked' AND used_at IS NULL AND revoked_at IS NOT NULL)
  ),
  CONSTRAINT credential_recovery_tokens_expires_after_created
    CHECK (expires_at > created_at),
  CONSTRAINT credential_recovery_tokens_used_after_created
    CHECK (used_at IS NULL OR used_at >= created_at),
  CONSTRAINT credential_recovery_tokens_used_before_expiry
    CHECK (used_at IS NULL OR used_at < expires_at),
  CONSTRAINT credential_recovery_tokens_revoked_after_created
    CHECK (revoked_at IS NULL OR revoked_at >= created_at),
  CONSTRAINT credential_recovery_tokens_timestamps_order
    CHECK (updated_at >= created_at)
);

CREATE INDEX idx_credential_recovery_tokens_user_created
  ON credential_recovery_tokens(user_id, created_at DESC);
CREATE INDEX idx_credential_recovery_tokens_active_expiry
  ON credential_recovery_tokens(expires_at)
  WHERE status = 'active';

CREATE TABLE teams (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  created_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  membership_revision BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT teams_name_not_blank CHECK (length(trim(name)) > 0),
  CONSTRAINT teams_membership_revision_positive
    CHECK (membership_revision >= 1),
  CONSTRAINT teams_timestamps_order CHECK (updated_at >= created_at),
  CONSTRAINT teams_deleted_after_created
    CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

CREATE TABLE team_memberships (
  team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  removed_at TIMESTAMPTZ,
  PRIMARY KEY (team_id, user_id),
  CONSTRAINT team_memberships_role_check
    CHECK (role IN ('admin', 'member')),
  CONSTRAINT team_memberships_status_check
    CHECK (status IN ('active', 'removed')),
  CONSTRAINT team_memberships_status_timestamp_check CHECK (
    (status = 'active' AND removed_at IS NULL)
    OR (status = 'removed' AND removed_at IS NOT NULL)
  ),
  CONSTRAINT team_memberships_timestamps_order
    CHECK (updated_at >= created_at),
  CONSTRAINT team_memberships_removed_after_created
    CHECK (removed_at IS NULL OR removed_at >= created_at)
);

CREATE INDEX idx_team_memberships_user_active
  ON team_memberships(user_id, team_id)
  WHERE status = 'active';
CREATE INDEX idx_team_memberships_team_active_role
  ON team_memberships(team_id, role, user_id)
  WHERE status = 'active';

CREATE TABLE team_invites (
  id UUID PRIMARY KEY,
  team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  invited_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  token_hash TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL,
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  expires_at TIMESTAMPTZ NOT NULL,
  accepted_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT team_invites_token_hash_check
    CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT team_invites_email_not_blank
    CHECK (length(trim(email)) > 0),
  CONSTRAINT team_invites_email_canonical
    CHECK (email = lower(trim(email))),
  CONSTRAINT team_invites_role_check
    CHECK (role IN ('admin', 'member')),
  CONSTRAINT team_invites_status_check
    CHECK (status IN ('pending', 'accepted', 'revoked')),
  CONSTRAINT team_invites_status_timestamps_check CHECK (
    (status = 'pending' AND accepted_at IS NULL AND revoked_at IS NULL)
    OR (status = 'accepted' AND accepted_at IS NOT NULL AND revoked_at IS NULL)
    OR (status = 'revoked' AND accepted_at IS NULL AND revoked_at IS NOT NULL)
  ),
  CONSTRAINT team_invites_expires_after_created
    CHECK (expires_at > created_at),
  CONSTRAINT team_invites_accepted_after_created
    CHECK (accepted_at IS NULL OR accepted_at >= created_at),
  CONSTRAINT team_invites_accepted_before_expiry
    CHECK (accepted_at IS NULL OR accepted_at < expires_at),
  CONSTRAINT team_invites_revoked_after_created
    CHECK (revoked_at IS NULL OR revoked_at >= created_at),
  CONSTRAINT team_invites_timestamps_order
    CHECK (updated_at >= created_at)
);

CREATE INDEX idx_team_invites_team_created
  ON team_invites(team_id, created_at DESC);
CREATE INDEX idx_team_invites_pending_expiry
  ON team_invites(team_id, expires_at)
  WHERE status = 'pending';

CREATE TABLE knowledge_collections (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  scope TEXT NOT NULL,
  owner_user_id UUID REFERENCES users(id) ON DELETE RESTRICT,
  team_id UUID REFERENCES teams(id) ON DELETE RESTRICT,
  acl_revision BIGINT NOT NULL DEFAULT 1,
  visibility_epoch BIGINT NOT NULL DEFAULT 1,
  collection_processing_revision BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT knowledge_collections_name_not_blank
    CHECK (length(trim(name)) > 0),
  CONSTRAINT knowledge_collections_scope_check
    CHECK (scope IN ('personal', 'team')),
  CONSTRAINT knowledge_collections_subject_shape_check CHECK (
    (scope = 'personal' AND owner_user_id IS NOT NULL AND team_id IS NULL)
    OR (scope = 'team' AND owner_user_id IS NULL AND team_id IS NOT NULL)
  ),
  CONSTRAINT knowledge_collections_acl_revision_positive
    CHECK (acl_revision >= 1),
  CONSTRAINT knowledge_collections_visibility_epoch_positive
    CHECK (visibility_epoch >= 1),
  CONSTRAINT knowledge_collections_processing_revision_positive
    CHECK (collection_processing_revision >= 1),
  CONSTRAINT knowledge_collections_timestamps_order
    CHECK (updated_at >= created_at),
  CONSTRAINT knowledge_collections_deleted_after_created
    CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

CREATE INDEX idx_knowledge_collections_personal_active
  ON knowledge_collections(owner_user_id, updated_at DESC)
  WHERE scope = 'personal' AND deleted_at IS NULL;
CREATE INDEX idx_knowledge_collections_team_active
  ON knowledge_collections(team_id, updated_at DESC)
  WHERE scope = 'team' AND deleted_at IS NULL;

CREATE TABLE knowledge_documents (
  id UUID PRIMARY KEY,
  collection_id UUID NOT NULL
    REFERENCES knowledge_collections(id) ON DELETE RESTRICT,
  current_version_id UUID,
  status TEXT NOT NULL DEFAULT 'processing',
  current_version_status TEXT GENERATED ALWAYS AS (
    CASE WHEN status = 'active' THEN 'active' ELSE NULL END
  ) STORED,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT knowledge_documents_status_check
    CHECK (status IN ('processing', 'active', 'tombstoned', 'deleted')),
  CONSTRAINT knowledge_documents_timestamps_order
    CHECK (updated_at >= created_at),
  CONSTRAINT knowledge_documents_deleted_after_created
    CHECK (deleted_at IS NULL OR deleted_at >= created_at),
  CONSTRAINT knowledge_documents_lifecycle_timestamp_shape CHECK (
    (
      status = 'processing'
      AND current_version_id IS NULL
      AND deleted_at IS NULL
    )
    OR (
      status = 'active'
      AND current_version_id IS NOT NULL
      AND deleted_at IS NULL
    )
    OR (status IN ('tombstoned', 'deleted') AND deleted_at IS NOT NULL)
  )
);

CREATE TABLE knowledge_document_versions (
  id UUID PRIMARY KEY,
  document_id UUID NOT NULL
    REFERENCES knowledge_documents(id) ON DELETE RESTRICT,
  file_id UUID NOT NULL REFERENCES files(id) ON DELETE RESTRICT,
  source_version BIGINT NOT NULL,
  visibility_epoch BIGINT NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'uploaded',
  content_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_document_versions_source_version_positive
    CHECK (source_version >= 1),
  CONSTRAINT knowledge_document_versions_visibility_epoch_positive
    CHECK (visibility_epoch >= 1),
  CONSTRAINT knowledge_document_versions_status_check CHECK (
    status IN (
      'uploaded',
      'processing',
      'failed',
      'active',
      'tombstoned',
      'purging',
      'deleted'
    )
  ),
  CONSTRAINT knowledge_document_versions_content_hash_check
    CHECK (content_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT knowledge_document_versions_timestamps_order
    CHECK (updated_at >= created_at),
  CONSTRAINT knowledge_document_versions_document_source_unique
    UNIQUE (document_id, source_version),
  CONSTRAINT knowledge_document_versions_document_id_unique
    UNIQUE (document_id, id),
  CONSTRAINT knowledge_document_versions_document_id_status_unique
    UNIQUE (document_id, id, status)
);

ALTER TABLE knowledge_documents
  ADD CONSTRAINT knowledge_documents_current_version_same_document_fk
  FOREIGN KEY (id, current_version_id)
  REFERENCES knowledge_document_versions(document_id, id)
  ON DELETE RESTRICT
  DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE knowledge_documents
  ADD CONSTRAINT knowledge_documents_active_version_status_fk
  FOREIGN KEY (id, current_version_id, current_version_status)
  REFERENCES knowledge_document_versions(document_id, id, status)
  ON DELETE RESTRICT
  DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX idx_knowledge_documents_collection_status
  ON knowledge_documents(collection_id, status, updated_at DESC);
CREATE INDEX idx_knowledge_document_versions_file
  ON knowledge_document_versions(file_id);
CREATE INDEX idx_knowledge_document_versions_document_status
  ON knowledge_document_versions(document_id, status, source_version DESC);

CREATE TABLE user_query_consent_state (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  query_consent_revision BIGINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_query_consent_state_revision_positive
    CHECK (query_consent_revision >= 1),
  CONSTRAINT user_query_consent_state_timestamps_order
    CHECK (updated_at >= created_at)
);

CREATE TABLE processor_governance_profiles (
  id UUID PRIMARY KEY,
  processor TEXT NOT NULL,
  endpoint_id TEXT NOT NULL,
  model_api_version TEXT NOT NULL,
  allowed_purposes TEXT[] NOT NULL,
  allowed_data_types TEXT[] NOT NULL,
  region TEXT NOT NULL,
  retention_policy TEXT NOT NULL,
  deletion_contract TEXT NOT NULL,
  training_use TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'candidate',
  governance_revision BIGINT NOT NULL,
  manifest_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT processor_governance_profiles_processor_not_blank
    CHECK (length(trim(processor)) > 0),
  CONSTRAINT processor_governance_profiles_endpoint_not_blank
    CHECK (length(trim(endpoint_id)) > 0),
  CONSTRAINT processor_governance_profiles_model_version_not_blank
    CHECK (length(trim(model_api_version)) > 0),
  CONSTRAINT processor_governance_profiles_purposes_shape CHECK (
    cardinality(allowed_purposes) >= 1
    AND array_ndims(allowed_purposes) = 1
    AND array_position(allowed_purposes, NULL) IS NULL
    AND allowed_purposes <@ ARRAY[
      'parse',
      'passage_embedding',
      'query_embedding',
      'rerank',
      'answer'
    ]::TEXT[]
  ),
  CONSTRAINT processor_governance_profiles_data_types_shape CHECK (
    cardinality(allowed_data_types) >= 1
    AND array_ndims(allowed_data_types) = 1
    AND array_position(allowed_data_types, NULL) IS NULL
    AND array_position(allowed_data_types, '') IS NULL
    AND array_to_string(allowed_data_types, ',')
      !~ '(^|,)[[:space:]]*(,|$)'
  ),
  CONSTRAINT processor_governance_profiles_region_not_blank
    CHECK (length(trim(region)) > 0),
  CONSTRAINT processor_governance_profiles_retention_not_blank
    CHECK (length(trim(retention_policy)) > 0),
  CONSTRAINT processor_governance_profiles_deletion_not_blank
    CHECK (length(trim(deletion_contract)) > 0),
  CONSTRAINT processor_governance_profiles_training_use_not_blank
    CHECK (length(trim(training_use)) > 0),
  CONSTRAINT processor_governance_profiles_status_check
    CHECK (status IN ('candidate', 'approved', 'retired')),
  CONSTRAINT processor_governance_profiles_revision_positive
    CHECK (governance_revision >= 1),
  CONSTRAINT processor_governance_profiles_manifest_hash_check
    CHECK (manifest_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT processor_governance_profiles_processor_revision_unique
    UNIQUE (processor, endpoint_id, governance_revision),
  CONSTRAINT processor_governance_profiles_binding_unique
    UNIQUE (processor, endpoint_id, id, governance_revision),
  CONSTRAINT processor_governance_profiles_active_binding_unique
    UNIQUE (processor, endpoint_id, id, governance_revision, status)
);

CREATE TABLE processor_governance_heads (
  processor TEXT NOT NULL,
  endpoint_id TEXT NOT NULL,
  status TEXT NOT NULL,
  active_profile_id UUID,
  active_governance_revision BIGINT,
  active_profile_status TEXT GENERATED ALWAYS AS (
    CASE WHEN status = 'active' THEN 'approved' ELSE NULL END
  ) STORED,
  head_revision BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (processor, endpoint_id),
  CONSTRAINT processor_governance_heads_processor_not_blank
    CHECK (length(trim(processor)) > 0),
  CONSTRAINT processor_governance_heads_endpoint_not_blank
    CHECK (length(trim(endpoint_id)) > 0),
  CONSTRAINT processor_governance_heads_status_check
    CHECK (status IN ('active', 'disabled')),
  CONSTRAINT processor_governance_heads_active_shape_check CHECK (
    (
      status = 'active'
      AND active_profile_id IS NOT NULL
      AND active_governance_revision IS NOT NULL
    )
    OR (
      status = 'disabled'
      AND active_profile_id IS NULL
      AND active_governance_revision IS NULL
    )
  ),
  CONSTRAINT processor_governance_heads_active_revision_positive
    CHECK (
      active_governance_revision IS NULL
      OR active_governance_revision >= 1
    ),
  CONSTRAINT processor_governance_heads_head_revision_positive
    CHECK (head_revision >= 1),
  CONSTRAINT processor_governance_heads_timestamps_order
    CHECK (updated_at >= created_at),
  CONSTRAINT processor_governance_heads_active_profile_fk
    FOREIGN KEY (
      processor,
      endpoint_id,
      active_profile_id,
      active_governance_revision,
      active_profile_status
    )
    REFERENCES processor_governance_profiles(
      processor,
      endpoint_id,
      id,
      governance_revision,
      status
    )
    ON DELETE RESTRICT
);

CREATE TABLE processing_consents (
  id UUID PRIMARY KEY,
  scope TEXT NOT NULL,
  collection_id UUID REFERENCES knowledge_collections(id) ON DELETE RESTRICT,
  user_id UUID REFERENCES users(id) ON DELETE RESTRICT,
  processor TEXT NOT NULL,
  endpoint_id TEXT NOT NULL,
  governance_profile_id UUID NOT NULL,
  governance_revision BIGINT NOT NULL,
  governance_head_revision BIGINT NOT NULL,
  purposes TEXT[] NOT NULL,
  data_types TEXT[] NOT NULL,
  policy_version TEXT NOT NULL,
  decision TEXT NOT NULL,
  consent_revision BIGINT NOT NULL,
  granted_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  decided_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ,
  superseded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT processing_consents_scope_check
    CHECK (scope IN ('collection', 'query')),
  CONSTRAINT processing_consents_subject_shape_check CHECK (
    (
      scope = 'collection'
      AND collection_id IS NOT NULL
      AND user_id IS NULL
    )
    OR (
      scope = 'query'
      AND collection_id IS NULL
      AND user_id IS NOT NULL
    )
  ),
  CONSTRAINT processing_consents_processor_not_blank
    CHECK (length(trim(processor)) > 0),
  CONSTRAINT processing_consents_endpoint_not_blank
    CHECK (length(trim(endpoint_id)) > 0),
  CONSTRAINT processing_consents_governance_revision_positive
    CHECK (governance_revision >= 1),
  CONSTRAINT processing_consents_head_revision_positive
    CHECK (governance_head_revision >= 1),
  CONSTRAINT processing_consents_purposes_shape CHECK (
    cardinality(purposes) >= 1
    AND array_ndims(purposes) = 1
    AND array_position(purposes, NULL) IS NULL
    AND purposes <@ ARRAY[
      'parse',
      'passage_embedding',
      'query_embedding',
      'rerank',
      'answer'
    ]::TEXT[]
  ),
  CONSTRAINT processing_consents_scope_purposes_check CHECK (
    (
      scope = 'collection'
      AND purposes <@ ARRAY[
        'parse',
        'passage_embedding',
        'rerank',
        'answer'
      ]::TEXT[]
    )
    OR (
      scope = 'query'
      AND purposes <@ ARRAY[
        'query_embedding',
        'rerank',
        'answer'
      ]::TEXT[]
    )
  ),
  CONSTRAINT processing_consents_data_types_shape CHECK (
    cardinality(data_types) >= 1
    AND array_ndims(data_types) = 1
    AND array_position(data_types, NULL) IS NULL
    AND array_position(data_types, '') IS NULL
    AND array_to_string(data_types, ',')
      !~ '(^|,)[[:space:]]*(,|$)'
  ),
  CONSTRAINT processing_consents_policy_version_not_blank
    CHECK (length(trim(policy_version)) > 0),
  CONSTRAINT processing_consents_decision_check
    CHECK (decision IN ('granted', 'revoked')),
  CONSTRAINT processing_consents_revision_positive
    CHECK (consent_revision >= 1),
  CONSTRAINT processing_consents_decided_after_created
    CHECK (decided_at >= created_at),
  CONSTRAINT processing_consents_expires_after_decision
    CHECK (expires_at IS NULL OR expires_at > decided_at),
  CONSTRAINT processing_consents_superseded_after_decision
    CHECK (superseded_at IS NULL OR superseded_at >= decided_at),
  CONSTRAINT processing_consents_timestamps_order
    CHECK (updated_at >= created_at),
  CONSTRAINT processing_consents_governance_profile_fk
    FOREIGN KEY (
      processor,
      endpoint_id,
      governance_profile_id,
      governance_revision
    )
    REFERENCES processor_governance_profiles(
      processor,
      endpoint_id,
      id,
      governance_revision
    )
    ON DELETE RESTRICT,
  CONSTRAINT processing_consents_governance_head_fk
    FOREIGN KEY (processor, endpoint_id)
    REFERENCES processor_governance_heads(processor, endpoint_id)
    ON DELETE RESTRICT
);

CREATE UNIQUE INDEX idx_processing_consents_current_collection_processor
  ON processing_consents(collection_id, processor)
  WHERE scope = 'collection' AND superseded_at IS NULL;
CREATE UNIQUE INDEX idx_processing_consents_current_query_processor
  ON processing_consents(user_id, processor)
  WHERE scope = 'query' AND superseded_at IS NULL;
CREATE UNIQUE INDEX idx_processing_consents_collection_revision
  ON processing_consents(collection_id, processor, consent_revision)
  WHERE scope = 'collection';
CREATE UNIQUE INDEX idx_processing_consents_query_revision
  ON processing_consents(user_id, processor, consent_revision)
  WHERE scope = 'query';
CREATE INDEX idx_processing_consents_profile
  ON processing_consents(governance_profile_id, governance_revision);

-- BIGSERIAL is an allocation-order cursor, not proof of transaction commit
-- order. Consumers must rescan claimable rows and may persist a high-watermark
-- only for a contiguous applied prefix; event_id is the replay identity.
CREATE TABLE knowledge_outbox (
  id BIGSERIAL PRIMARY KEY,
  event_id UUID NOT NULL UNIQUE,
  aggregate_type TEXT NOT NULL,
  aggregate_key TEXT NOT NULL,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL,
  headers JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending',
  attempt_count INTEGER NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  locked_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_outbox_aggregate_type_not_blank
    CHECK (length(trim(aggregate_type)) > 0),
  CONSTRAINT knowledge_outbox_aggregate_key_not_blank
    CHECK (length(trim(aggregate_key)) > 0),
  CONSTRAINT knowledge_outbox_event_type_not_blank
    CHECK (length(trim(event_type)) > 0),
  CONSTRAINT knowledge_outbox_payload_object
    CHECK (jsonb_typeof(payload) = 'object'),
  CONSTRAINT knowledge_outbox_headers_object
    CHECK (jsonb_typeof(headers) = 'object'),
  CONSTRAINT knowledge_outbox_status_check
    CHECK (status IN ('pending', 'processing', 'published', 'failed')),
  CONSTRAINT knowledge_outbox_attempt_count_non_negative
    CHECK (attempt_count >= 0),
  CONSTRAINT knowledge_outbox_status_timestamps_check CHECK (
    (
      status = 'pending'
      AND locked_at IS NULL
      AND published_at IS NULL
    )
    OR (
      status = 'processing'
      AND locked_at IS NOT NULL
      AND published_at IS NULL
    )
    OR (
      status = 'published'
      AND published_at IS NOT NULL
    )
    OR (status = 'failed' AND published_at IS NULL)
  ),
  CONSTRAINT knowledge_outbox_last_error_not_blank
    CHECK (last_error IS NULL OR length(trim(last_error)) > 0),
  CONSTRAINT knowledge_outbox_available_after_created
    CHECK (available_at >= created_at),
  CONSTRAINT knowledge_outbox_locked_after_created
    CHECK (locked_at IS NULL OR locked_at >= created_at),
  CONSTRAINT knowledge_outbox_published_after_created
    CHECK (published_at IS NULL OR published_at >= created_at),
  CONSTRAINT knowledge_outbox_timestamps_order
    CHECK (updated_at >= created_at)
);

CREATE INDEX idx_knowledge_outbox_pending
  ON knowledge_outbox(available_at, id)
  WHERE status = 'pending';
CREATE INDEX idx_knowledge_outbox_aggregate
  ON knowledge_outbox(aggregate_type, aggregate_key, id);
