REVOKE EXECUTE ON FUNCTION
  agent_artifact_authorize(TEXT,UUID,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT),
  agent_artifact_attach(TEXT,TEXT,UUID,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT)
  FROM agent_artifact_control;
REVOKE EXECUTE ON FUNCTION
  agent_product_validate_artifact_authority(TEXT,UUID,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT)
  FROM agent_product_owner;
REVOKE EXECUTE ON FUNCTION
  agent_effect_artifact_fence(TEXT,UUID,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,TEXT)
  FROM agent_product_owner;
REVOKE EXECUTE ON FUNCTION
  agent_orchestrator_artifact_fence(UUID,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,BIGINT)
  FROM agent_product_owner;
DO $schema_acl$ BEGIN
  EXECUTE format('REVOKE ALL ON SCHEMA %I FROM agent_artifact_control',current_schema());
END
$schema_acl$;
DROP FUNCTION agent_artifact_attach(TEXT,TEXT,UUID,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT);
DROP FUNCTION agent_artifact_authorize(TEXT,UUID,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT);
DROP FUNCTION agent_product_validate_artifact_authority(TEXT,UUID,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT);
DROP FUNCTION agent_effect_artifact_fence(TEXT,UUID,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,TEXT);
DROP FUNCTION agent_orchestrator_artifact_fence(UUID,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,BIGINT,TEXT,TEXT,TEXT,BIGINT);
DROP ROLE agent_artifact_control;
