DO $guard$
BEGIN
  IF EXISTS (SELECT 1 FROM chat_agent_goals) THEN
    RAISE EXCEPTION USING
      ERRCODE = '55000',
      MESSAGE = 'CHAT_AGENT_GOALS_DOWN_DATA_EXISTS';
  END IF;
END
$guard$;

REVOKE ALL ON FUNCTION chat_agent_create_goal(
  UUID,UUID,UUID,TEXT,INTEGER,TIMESTAMPTZ
), chat_agent_change_goal(
  UUID,UUID,UUID,BIGINT,TEXT,TEXT,INTEGER,TEXT,TIMESTAMPTZ
), chat_agent_cancel_goal(
  UUID,UUID,UUID,BIGINT,TIMESTAMPTZ
), chat_agent_start_goal_round(
  UUID,UUID,UUID,BIGINT,INTEGER,TIMESTAMPTZ
) FROM go_api_runtime;
REVOKE ALL ON chat_agent_goals FROM go_api_runtime;

DROP FUNCTION chat_agent_start_goal_round(UUID,UUID,UUID,BIGINT,INTEGER,TIMESTAMPTZ);
DROP FUNCTION chat_agent_cancel_goal(UUID,UUID,UUID,BIGINT,TIMESTAMPTZ);
DROP FUNCTION chat_agent_change_goal(UUID,UUID,UUID,BIGINT,TEXT,TEXT,INTEGER,TEXT,TIMESTAMPTZ);
DROP FUNCTION chat_agent_create_goal(UUID,UUID,UUID,TEXT,INTEGER,TIMESTAMPTZ);
DROP TABLE chat_agent_goals;
